FONT_NAME = "Sofia Pro"
FONT_COLOR = "#000000"

BACKGROUND_IMAGE_FILE_NAME = "background.jpg"

TITLE_FONT_SIZE = 110
TITLE_TOP_OFFSET = 80
TITLE_BACKGROUND_COLOR = "#ffffff"
TITLE_BACKGROUND_MARGIN = 20
TITLE_BACKGROUND_BORDER_RADIUS = 20
TITLE_BACKGROUND_TRANSPARENCY = 164

OPTION_TILE_SIDE = 200
OPTION_TILE_X_SPACING = 100
OPTION_TILE_Y_SPACING = 40
OPTION_TILE_BACKGROUND_COLOR = "white"
OPTION_TILE_BACKGROUND_TRANSPARENCY = 164
OPTION_TILE_BACKGROUND_BORDER_RADIUS = 20

LIST_OPTION_FONT_SIZE = 60
LIST_OPTION_LEFT_OFFSET = 200
LIST_OPTION_Y_SPACING = 40
LIST_OPTION_HEIGHT = 50
LIST_OPTION_MIN_WIDTH = 500
LIST_OPTION_TEXT_SIDE_MARGIN = 10
LIST_OPTION_BACKGROUND_COLOR = "white"
LIST_OPTION_BACKGROUND_TRANSPARENCY = 190
LIST_OPTION_BACKGROUND_BORDER_RADIUS = 10
