FONT_NAME = "Sofia Pro"
FONT_COLOR = "#000000"
MENU_TITLE_FONT_SIZE = 110
MENU_TITLE_TOP_OFFSET = 80


MENU_TILES_SIDE = 200
MENU_TILES_X_SPACING = 100
MENU_TILES_Y_SPACING = 40

MENU_OPTIONS_LIST_FONT_SIZE = 30
MENU_OPTIONS_LIST_LEFT_OFFSET = 40
MENU_OPTIONS_Y_SPACING = 40
MENU_LIST_OPTIONS_HEIGHT = 20
MENU_LIST_OPTIONS_MIN_WIDTH = 90

MAIN_MENU_TITLE = "Wybierz rodzaj skrzyżowania"
MAIN_MENU_OPTIONS_COLUMNS_NUMBER = 3

INTERSECTION_MENU_TITLE = "Wybierz rodzaj manewru"
INTERSECTION_MENU_OPTIONS_COLUMNS_NUMBER = 3
