FONT_NAME = "Sofia Pro"
FONT_COLOR = "#000000"
MENU_TITLE_FONT_SIZE = 120
MENU_OPTIONS_TITLE_FONT_SIZE = 40
MENU_OPTIONS_IMAGE_SIDE = 200
MENU_TITLE_TOP_OFFSET = 100
MENU_OPTIONS_X_SPACING = 10
MENU_OPTIONS_Y_SPACING = 10

MAIN_MENU_TITLE = "Choose Animation"
MAIN_MENU_OPTIONS_COLUMNS_NUMBER = 3

INTERSECTION_MENU_TITLE = "Choose Intersection Manoeuvre"
INTERSECTION_MENU_OPTIONS_COLUMNS_NUMBER = 3
