CONTROL_INSTRUCTIONS_DIR = "animations/animations_generators/control_instructions"
PLAYBACK_ANIMATIONS = True
BACKGROUND_COLOR = "#7e6767"
PRIMARY_CAR_COLOR = "#d41b00"
SECONDARY_CAR_COLOR = "#0084d4"
